name: CD
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: node:14.13.1
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules-
      - name: Install Node modules
        run: npm install
      - name: Build
        run: BUILD_NUMBER=$GITHUB_SHA npm run build
      - name: Pack
        run: .github/workflows/pack.sh
      - name: Persist package
        uses: actions/upload-artifact@v1
        with:
          name: package
          path: package/
      - name: Persist build dir
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build/
      - name: Persist lib dir
        uses: actions/upload-artifact@v1
        with:
          name: lib
          path: lib/
      - name: Test
        run: npm test
      - name: Deploy to NPM
        run: .github/workflows/deploy_to_npm.sh
        env:
          NPM_AUTH: ${{ secrets.NPM_AUTH }}
      - name: Deploy to GitHub pages
        run: .github/workflows/deploy_to_gh_pages.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
