name: CD
on:
  push:
    tags: ["v*"]
  release:
    types: [published]
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  build:
    name: Build
    uses: andrewscwei/workflows/.github/workflows/node-build.yml@master
    with:
      artifacts-path: build/
  deploy:
    name: Deploy
    needs: [build]
    uses: andrewscwei/workflows/.github/workflows/npm-deploy.yml@master
    with:
      artifacts-name: ${{ needs.build.outputs.artifacts-name }}
      artifacts-path: ${{ needs.build.outputs.artifacts-path }}
      create-release: true
    secrets:
      npm-auth-token: ${{ secrets.NPM_AUTH }}
  docs:
    name: Docs
    uses: andrewscwei/workflows/.github/workflows/gh-pages-deploy.yml@master
    with:
      branch-name: gh-pages
      deploy-path: .gh-pages
      run-command: npm run pages
  notify:
    name: Notify
    needs: [build, deploy, docs]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/telegram-action@v1.0.0
        with:
          success: ${{ needs.build.result == 'success' && needs.deploy.result == 'success' && needs.docs.result == 'success' }}
          bot-token: ${{ secrets.TELEGRAM_DEVOPS_BOT_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_DEVOPS_CHAT_ID }}
